In [1]:
import utils
import relevance
import os
import sys
import pandas as pd
import importlib
importlib.reload(utils)
importlib.reload(relevance)

In [2]:
max_interval = 7
ms, ms_json   = utils.scan_ms(['data science', 'applied science', 'machine learning'])
amz, amz_json = utils.scan_amazon(['data science', 'applied science', 'machine learning'])

ms_relevant  = utils.export_excel(ms, "microsoft", max_interval=max_interval)
amz_relevant = utils.export_excel(amz, "amazon", max_interval=max_interval)

Saved 117 Microsoft jobs → ms_jobs_2026_08_04.json
Saved 128 Amazon jobs → amazon_jobs_2026_08_04.json
Wrote 12/117 relevant jobs → jobs_2026_08_04.xlsx (sheet 'microsoft')
Wrote 25/128 relevant jobs → jobs_2026_08_04.xlsx (sheet 'amazon')

In [7]:
import json

with open("ms_jobs_2026_07_24.json", "r") as f:
    data = json.load(f)      # data is now a list of dictionaries

print(type(data))
pd.DataFrame(data['results'])

<class 'dict'>

,job_id,title,posted,interval_days,location,href
0,1970393556929384,Senior Data Engineer & Data Science Engineer U...,1 day ago,1.000000,None,https://apply.careers.microsoft.com/careers/jo...
1,1970393556860577,"Principal Product Manager, Data Science & Mark...",15 days ago,15.000000,None,https://apply.careers.microsoft.com/careers/jo...
2,1970393556823722,"Principal, Data Science & Analytics United Sta...",2 months ago,60.000000,None,https://apply.careers.microsoft.com/careers/jo...
3,1970393556868271,Applied Science: PhD Microsoft AI Internship O...,2 days ago,2.000000,None,https://apply.careers.microsoft.com/careers/jo...
4,1970393556875996,"Principal Data Scientist United States, Washin...",11 hours ago,0.458333,None,https://apply.careers.microsoft.com/careers/jo...
...,...,...,...,...,...,...
110,1970393556857971,Principal Research Software Engineer United St...,2 months ago,60.000000,None,https://apply.careers.microsoft.com/careers/jo...
111,1970393556939499,"Senior Software Engineer United States, Washin...",3 days ago,3.000000,None,https://apply.careers.microsoft.com/careers/jo...
112,1970393556927941,"Senior Software Engineer United States, Washin...",3 days ago,3.000000,None,https://apply.careers.microsoft.com/careers/jo...
113,1970393556912055,"Principal Software Engineer United States, Was...",1 month ago,30.000000,None,https://apply.careers.microsoft.com/careers/jo...
114,1970393556815539,"Software Engineer II United States, Washington...",1 month ago,30.000000,None,https://apply.careers.microsoft.com/careers/jo...

In [ ]:
1970393556860577
1970393556823722

In [6]:
for t in ms.title.unique():
    print(t)

Technical Program Manager I - Finance Data & Experiences United States, Washington, Redmond
Technical Program Manager II - Finance Data & Experiences United States, Washington, Redmond
Senior Applied Threat Intelligence Analyst - Microsoft Security Threat Response United States, Washington, Redmond
Principal Applied Threat Intelligence Analyst - Microsoft Security Threat Response United States, Washington, Redmond
Applied Scientist II United States, Washington, Redmond + 1 more
Principal Data Scientist United States, Washington, Redmond + 1 more
Applied Scientist II United States, Washington, Redmond
Principal Security Research Manager, Applied Threat Intel & Threat Response - Microsoft Security United States, Washington, Redmond + 1 more
Senior Software Engineer United States, Washington, Redmond
Software Engineer II United States, Washington, Redmond
Senior Data Engineer & Data Science Engineer United States, Washington, Redmond + 4 more
Cloud Solutions Architect - Azure Data & AI Solutions United States, Washington, Redmond + 3 more
Senior AI Engineer, Security AI United States, Washington, Redmond + 1 more
Senior Software Engineer, Security AI United States, Washington, Redmond + 1 more
Director, Digital Experience United States, Washington, Redmond + 3 more
Applied Scientist United States, Washington, Redmond + 1 more
Principal Data Engineering Manager United States, Washington, Redmond
Sr. Demand Planner United States, Washington, Redmond + 1 more
Senior Data Engineer United States, Washington, Redmond
Principal Software Engineer United States, Washington, Redmond
Applied Science: PhD Microsoft AI Internship Opportunities - Redmond United States, Washington, Redmond
Senior Finance Manager, Finance Data & Experiences United States, Washington, Redmond
Principal Applied Threat Intelligence Manager United States, Washington, Redmond + 1 more
AI Business Solutions & Security GTM Lead United States, Washington, Redmond
Principal Software Engineer - Microsoft Digital United States, Washington, Redmond
Applied Scientist II (Bing Places) United States, Washington, Redmond + 1 more
Senior Applied Scientist (Bing Places) United States, Washington, Redmond
Data Engineer United States, Washington, Redmond
Principal Software Engineer - Data, Personalization - Microsoft AI United States, Washington, Redmond
Senior Technical Program Manager, Data Engineering United States, Washington, Redmond
Principal Software Engineer - Identity United States, Washington, Redmond
Senior Applied Scientist United States, Washington, Redmond + 1 more
Senior Data Scientist United States, Washington, Redmond + 8 more
Surface Consumer Lead, Microsoft Digital Sales, Americas United States, Washington, Redmond
Principal Applied Scientist United States, Washington, Redmond
Principal Software Engineer - CoreAI United States, Washington, Redmond + 1 more
Senior Data Scientist, AI Infrastructure United States, Washington, Redmond + 1 more
Senior Software Engineer, MS Edge Growth United States, Washington, Redmond
Senior Research Engineer United States, Washington, Redmond
Principal Software Engineering Manager, CoreAI United States, Washington, Redmond + 2 more

In [ ]:
pd.concat([res1, res2]).drop_duplicates().sort_values("id").id.value_counts()

id
1970393556864459    2
1970393556868711    2
1970393556621351    1
1970393556749538    1
1970393556826534    1
1970393556836404    1
1970393556851873    1
1970393556858380    1
1970393556860577    1
1970393556862590    1
1970393556864437    1
1970393556864732    1
1970393556864744    1
1970393556867409    1
1970393556867420    1
1970393556868060    1
Name: count, dtype: int64

Appended 10 jobs to sheet 'applied' in ms_2026_05_19.xlsx

In [6]:
import subprocess
import json
import pandas as pd

subprocess.run(["python", "test3.py"], check=True)

with open("ms_jobs.json", "r", encoding="utf-8") as f:
    jobs = json.load(f)

df = pd.DataFrame(jobs)
df["interval_days"] = df.posted.apply(lambda s: utils.interval_to_hours(s))
df.head()

,title,posted,location,href,id,interval_days
0,Principal Technical Program Manager - Applied ...,2 months ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556824835,60.0
1,"Member of Technical Staff, Applied AI Engineer...",19 days ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556769429,19.0
2,Applied Scientist II / Senior Applied Scientis...,5 months ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556650765,150.0
3,Senior Applied Scientists and Principal Applie...,5 months ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556625171,150.0
4,"Principal Applied Scientist United States, Was...",4 months ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556668240,120.0

In [9]:
df.query("interval_days < 7")

,title,posted,location,href,id,interval_days
6,"Senior Applied Scientist United States, Washin...",3 days ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556866161,3.0
20,"Senior Applied Scientist United States, Washin...",4 days ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556851873,4.0
21,Manager- Applied Sciences / Machine Learning U...,5 days ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556852769,5.0
32,"Applied Scientist II United States, Washington...",4 days ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556866225,4.0
36,Senior Applied Scientist (Bing Places) United ...,5 days ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556856829,5.0
37,"Senior Applied Scientist United States, Washin...",2 days ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556751830,2.0
38,"Senior Applied Scientist United States, Washin...",1 day ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556866472,1.0
40,Applied Scientist II (Bing Places) United Stat...,5 days ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556858338,5.0
44,"Senior Research Engineer United States, Washin...",4 days ago,None,https://apply.careers.microsoft.com/careers/jo...,1970393556619968,4.0

In [12]:
df.query("interval_days < 4").iloc[0,3]

'https://apply.careers.microsoft.com/careers/job/1970393556866161'

In [6]:
df.query("interval_days < 4").to_excel("ms_applied_scientist_3_24.xlsx")